# Site/Blog Configuration

# Title of the Site/Blog
title = ".Nikolas"

# Description of the Site/Blog
description = "Hobbyist Dev & Gleam enthusiast"

# Author of the Site/Blog
# Will be set as post author if not define in the post metadata
author = "Nikolas"

# Base URL of the Site/Blog
baseUrl = "blog/"

# The Directory where static files will be generated for deployment
# Default: "public" if not defined
publishDir = "public"

# The Directory where content files are located
# Default: "content" if not defined
contentDir = "content"

# The Theme to use for the Site/Blog
# Default: "default" if not defined
theme = "willyboar"

# The Number of posts to display per page
# pagination = 5

# Navigation menu (order matters)
[menus]
  [[menus.main]]
    name = "Home"
    pageRef = "/"
    weight = 10

  [[menus.main]]
    name = "About"
    pageRef = "/about"
    weight = 20

  [[menus.main]]
    name = "Tags"
    pageRef = "/tags/"
    weight = 30
